apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo1
    access: proxy
    url: http://tempo:3200
    editable: false
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki1
        spanStartTimeShift: "5m"
        spanEndTimeShift: "5m"
        customQuery: true
        query: '{${__tags}} |= "${__span.traceId}" |= "${__span.spanId}"'
        tags:
          - key: "service.name"
            value: "job"
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prom1
    url: http://prometheus:9090
    editable: false
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.49.0
      timeInterval: 15s
  - name: Loki
    type: loki
    uid: loki1
    access: proxy
    url: http://loki:3100
    editable: false
    basicAuth: false
    jsonData:
      timeout: 60
      maxLines: 1000
